---
apiVersion: v1
kind: Route
metadata:
  name: caddy-test
spec:
  path: /metrics
  to:
    kind: Service
    name: caddy-test
    weight: 100
  port:
    targetPort: metrics
  tls:
    termination: edge
  wildcardPolicy: None