---
apiVersion: v1
kind: Service
metadata:
  name: caddy-test
spec:
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 9180
      targetPort: 9180
  selector:
    app: caddy-test